INSERT INTO blogful_articles (title, date_published, content)
VALUES
('Title 1', now(), 'Content one'),
('Title 2', now(), 'Content two'),
('Title 3', now(), 'Content three'),
('Title 4', now(), 'Content four'),
('Title 5', now(), 'Content five'),
('Title 6', now(), 'Content six'),
('Title 7', now(), 'Content seven'),
('Title 8', now(), 'Content eight'),
('Title 9', now(), 'Content nine'),
('Title 10', now(), 'Content ten'),
('Title 11', now(), 'Content eleven'),
('Title 12', now(), 'Content twelve'),
('Title 13', now(), 'Content thirteen'),
('Title 14', now(), 'Content forteen'),
('Title 15', now(), 'Content sixteen'),
('Title 16', now(), 'Content sixteen'),
('Title 17', now(), 'Content seventeen'),
('Title 18', now(), 'Content eighteen'),
('Title 19', now(), 'Content nineteen'),
('Title 20', now(), 'Content twenty');